---

- name: Ensure backup user exists
  user: name={{backup.user}}

- name: Ensure backup group exists
  user: name={{backup.group}}

- name: Ensure backup directories exits
  file: path={{item}} state=directory owner={{backup.user}} group={{backup.group}}
  with_items:
  - "{{backup.home}}"
  - "{{backup.work}}"
  - "{{backup.logdir}}"

- name: Install duply
  template: src=duply.sh.j2 dest=/usr/bin/duply owner={{backup.user}} group={{backup.group}} mode=0755

- name: Create profile directories
  file: path={{backup.home}}/{{item.name}} state=directory mode=0700 owner={{item.user|default(backup.user)}} group={{item.group|default(backup.group)}} 
  with_items: "{{profiles}}"

- name: Configure profiles
  template: src=conf.j2 dest={{backup.home}}/{{item.name}}/conf owner={{item.user|default(backup.user)}} group={{item.group|default(backup.group)}} 
  with_items: "{{profiles}}"

- name: Configure exclude lists
  template: src=exclude.j2 dest={{backup.home}}/{{item.name}}/exclude owner={{item.user|default(backup.user)}} group={{item.group|default(backup.group)}} 
  with_items: "{{profiles}}"

- name: Configure pre scripts
  template: src=pre.j2 dest={{backup.home}}/{{item.name}}/pre owner={{item.user|default(backup.user)}} group={{item.group|default(backup.group)}} 
  with_items: "{{profiles}}"

- name: Configure post scripts
  template: src=post.j2 dest={{backup.home}}/{{item.name}}/post owner={{item.user|default(backup.user)}} group={{item.group|default(backup.group)}} 
  with_items: "{{profiles}}"

- name: Configure restore scripts
  template: src=restore.j2 dest={{backup.home}}/{{item.name}}/restore owner={{item.user|default(backup.user)}} group={{item.group|default(backup.group)}} 
  with_items: "{{profiles}}"

- name: Create work directories
  file: state=directory path={{backup.work}}/{{item.name}} owner={{item.user|default(backup.user)}} group={{item.group|default(backup.group)}}  
  with_items: "{{profiles}}"

- name: Setup cron
  template: src=cron.j2 dest=/etc/cron.d/backup owner=root group=root mode=0644
  when: backup.cron

- name: Create log files
  file: state=touch path={{backup.logdir}}/{{item.name}}.log owner={{item.user|default(backup.user)}} group={{item.group|default(backup.group)}}
  with_items: "{{profiles}}"
  changed_when: False

- name: Configure logrotate
  template: src=logrotate.j2 dest=/etc/logrotate.d/backup owner=root group=root mode=0644
