- name: Install packages
  apt: 
    name: "{{ item }}"
    state: "latest"
    update_cache: "yes"
  with_items:
  - cron
  - gzip
  - python-boto
  - s3cmd
  - ncftp
  - duplicity
  - lftp
  - python-paramiko
  - python-pycryptopp
  - python-gobject-2
  - python-pexpect