- name: Install dependecies
  become: yes
  apt:
    name: "{{ item }}"
    state: "present"
  with_items:
  - cron
  - gzip
  - python-boto
  - s3cmd
  - ncftp
  - lftp
  - python-paramiko
  - python-pycryptopp
  - python-gobject-2
  - python-pexpect
  - librsync1
  - gnupg
  - python-lockfile
  - python-dev
  - librsync-dev
  - python-setuptools
  - build-essential

- name: check if duplicity is installed
  register: _duplicity_status
  shell: >
    duplicity --version
  failed_when: no

- name: parse duplicity version
  set_fact:
    _duplicity_version: "{{ _duplicity_status.split()[1] is version(mrbackup_duplicity_version, '>=') }}"

- import_tasks: install.yml
  when: _duplicity_version or mrbackup_force_install

- name: uninstall compiler (for security best-practices)
  apt:
    name: build-essential
    state: absent

- import_tasks: configure.yml
  when: not backup.remove

- import_tasks: remove.yml
  when: backup.remove
