- include: install.deb.yml
  when: ansible_os_family == "Debian" and not backup.remove

- include: install.red.yml
  when: ansible_os_family == "RedHat" and not backup.remove

- include: configure.yml
  when: not backup.remove

- include: remove.yml
  when: backup.remove
